name: AdvancementRace
version: 1.0-SNAPSHOT
main: io.github.sriyaankvad.advancementrace.AdvancementRace
api-version: 1.16.5
description: Starts a competition between players to see who will be the last to fail to get a specific advancement
author: Sriyaank Vadlamani

commands:
  advacementrace:
    description: Primary interface for the Advancementrace plugin.
    usage: /<command> start, /<command> add (playername), /<command> list
    permission: AdvancementRace.advancementrace