name: AdvancementRace
version: 1.0-SNAPSHOT
main: io.github.sriyaankvad.advancementrace.Advancementrace
api-version: 1.17
authors: [ Sriyaank_Vadlamani ]
description: A minigame where multiple people race to complete an advancement before time runs out

commands:
  advancementrace:
    description: Primary interface for the Advancementrace plugin.
    usage: /<command> start, /<command> add (playername), /<command> list
    permission: AdvancementRace.advancementrace