name: MinecraftRandomizer
version: ${project.version}
main: io.github.sriyaankvad.minecraftrandomizer.minecraftrandomizer.MinecraftRandomizer
api-version: 1.17
authors: [ Sriyaank_Vadlamani ]
description: Randomizes the drop of each block
