name: PlayerCompass
version: ${project.version}
main: io.github.ashrityarava.playercompass.PlayerCompass
api-version: 1.16
authors: [ Ashrit_Yarava ]
description: A compass to track players with
website: https://ashrit-yarava.github.io/plugins/compass

commands:
  compass:
    description: Control where compass points to.
    usage: /compass <player name>, /compass reset
    permission: Compass.compass