name: PlayerCompass
version: ${project.version}
main: io.github.ashrityarava.playercompass.PlayerCompass
api-version: 1.16
authors: [ Ashrit_Yarava ]
description: A player compass.

commands:
  compass:
    usage: /compass give, /compass <player name>
    description: A compass that can be used to track the locations of other players.
    permission: PlayerCompass.compass

permissions:
  PlayerCompass.compass:
    description: Allows user to use player compass.
    default: true